<?php $resourceType = $this->resourceType ?? 'resource'; ?>
<?php $components = is_array($this->components) ? $this->components : []; ?>
<?php
echo $this->partial('common/block-template/browse-preview-base.phtml', [
        'layoutSetting' => 'grid',
        'controller' => $resourceType,
        'showThumbnail' => in_array('thumbnail', $components),
        'showHeading' => in_array('resource-heading', $components),
        'showBody' => in_array('resource-body', $components),
        'resources' => $this->resources,
        'previewTitle' => $this->heading,
        'linkText' => $this->linkText
    ]);
?>